site_name: LFSIR
site_url: https://iran-open-data.github.io/LFSIR/
repo_url: https://github.com/Iran-Open-Data/LFSIR

theme:
  name: material
  features:
    # - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    # - header.autohide
    - toc.follow
    # - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - content.tooltips

nav:
  - Home:
    - README.md
  # - Usage: usage.md
  - API Reference:
    - api/README.md
    - Setup Functions:
      - lfsir.setup: api/setup.md
      - lfsir.setup_config: api/setup_config.md
    - Data Loading Functions:
      - lfsir.load_table: api/load_table.md
    - Data Addition Functions:
      - lfsir.add_attribute: api/add_attribute.md
  - Data Reference:
    - tables/README.md
    - Questions:
      - Form 3:
        - "1384 - 1386": tables/form3_1384.md
        - "1387 - now": tables/form3_1387.md
    - Raw Data: tables/raw/data.md
    - Cleaned Data: tables/cleaned/data.md

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [lfsir]
          options:
            docstring_style: numpy
            show_source: false

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.inlinehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
