[project]
name = "lfsir"
version = "0.6.0"
description = ""
readme = "README.md"
authors = [
  { name = "Mohammad Amin Alavian", email = "m.amin.alavian@gmail.com" }
]
keywords = ["iran", "survey", "data", "socioeconomic"]
requires-python = ">=3.10"
dependencies = [
  "bssir"
]

[project.optional-dependencies]
dev = [
  "bssir[dev]",
]
maintain = [
  "bssir[maintain]",
]
notebook = [
  "bssir[notebook]",
]

[project.urls]
Homepage = "https://github.com/Iran-Open-Data/LFSIR"
Repository = "https://github.com/Iran-Open-Data/LFSIR"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
lfsir = ["**/*.yaml", "**/*.csv"]
