# Package Name
package_name: LFSIR

# Local Directory
local_dir: Data
in_root: true

# Years (list of years or range in for of: "first_year - last_year")
years: "1384-1402"

# Local Settings
local_settings: config/lfsir_settings.yaml

# Folder Names
folder_names:
  cached: LFSIR/_cache
  metadata: LFSIR/_metadata
  original: LFSIR/1_original
  unpacked: LFSIR/2_unpacked
  extracted: LFSIR/3_extracted
  cleaned: LFSIR/4_cleaned
  external: External_Data
  maps: Maps
