# Package Name
package_name: LFSIR

# Local Directory
local_dir: Data/LFSIR
in_root: true

# Years (list of years or range in for of: "first_year - last_year")
years: "1384-1402"

# Local Settings
local_settings: config/lfsir_settings.yaml
